--Project 1 Table Creation Script
--Ian
-- May 10th, 2018

--The employee table
CREATE TABLE EMPLOYEE (
    EMPLOYEE_ID INTEGER PRIMARY KEY,
    EMPLOYEE_USERNAME VARCHAR2(100) UNIQUE NOT NULL,
    EMPLOYEE_PASSWORD VARCHAR2(100) NOT NULL,
    EMPLOYEE_EMAIL VARCHAR2(100) NOT NULL,
    EMPLOYEE_FIRSTNAME VARCHAR2(100) NOT NULL,
    EMPLOYEE_LASTNAME VARCHAR2(100) NOT NULL,
    EMPLOYEE_ACTIVE_REI_REQS INTEGER
);

--Sequence for employee primary key
CREATE SEQUENCE EMPLOYEE_ID_INC_PK
    MINVALUE 1
    START WITH 1
    INCREMENT BY 1;

--Trigger for auto-incrementing employee primary key
CREATE OR REPLACE TRIGGER EMPLOYEE_ID_INCREMENT
    BEFORE INSERT ON EMPLOYEE
    FOR EACH ROW
BEGIN
    SELECT EMPLOYEE_ID_INC_PK.NEXTVAL INTO :NEW.EMPLOYEE_ID FROM DUAL;
END;


    