--SQL Lab Assignment
--Ian
--May 5th, 2018

--SECTION 2 : SQL Queries

--2.1 SELECT

SELECT * FROM EMPLOYEE;
/

SELECT * FROM EMPLOYEE WHERE LASTNAME = 'King';
/

SELECT * FROM EMPLOYEE WHERE FIRSTNAME = 'Andrew' AND REPORTSTO IS NULL;
/

--2.2 ORDER BY

SELECT * FROM ALBUM ORDER BY TITLE DESC;
/

SELECT FIRSTNAME, CITY FROM CUSTOMER ORDER BY CITY DESC;
/

--2.3 INSER INTO

INSERT INTO GENRE (GENREID, NAME) VALUES (26, 'Post Rock');
INSERT INTO GENRE (GENREID, NAME) VALUES (27, 'Indie Rock');
INSERT INTO EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE ,REPORTSTO ,BIRTHDATE, HIREDATE ,ADDRESS, CITY,
    STATE, COUNTRY, POSTALCODE, PHONE, FAX, EMAIL)
    VALUES
    (9, 'Solo', 'Han', 'IT Staff' , 6, TO_DATE('31-jan-1987', 'DD-MM-YYYY') , TO_DATE('05-may-2018', 'DD-MM-YYYY'), 
    '2318 243rd Pl', 'Calgary', 'AB', 'Canada', 'T5K 2N1', '1-234-234-3343', '1-234-234-3344', 'hansolo@gmail.com');
INSERT INTO EMPLOYEE (EMPLOYEEID, LASTNAME, FIRSTNAME, TITLE ,REPORTSTO ,BIRTHDATE, HIREDATE ,ADDRESS, CITY,
    STATE, COUNTRY, POSTALCODE, PHONE, FAX, EMAIL)
    VALUES
    (10, 'Skywalker', 'Luke', 'IT Staff' , 6, TO_DATE('31-jan-1989', 'DD-MM-YYYY') , TO_DATE('05-may-2018', 'DD-MM-YYYY'), 
    '2318 243rd Pl', 'Calgary', 'AB', 'Canada', 'T5K 2N1', '1-234-234-3343', '1-234-234-3344', 'lskywalker@gmail.com');
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, COMPANY, ADDRESS, CITY,
    STATE, COUNTRY, POSTALCODE, PHONE, FAX, EMAIL, SUPPORTREPID)
    VALUES
    (60, 'Jack', 'Sky', 'Fatburger', '2343 Blue Pl', 'Calgary', 'AB', 'Canada', 'T5K 2N1',
    '1-432-234-4333', '1-234-343-2343', 'jsky@gmail.com', 3);
INSERT INTO CUSTOMER (CUSTOMERID, FIRSTNAME, LASTNAME, COMPANY, ADDRESS, CITY,
    STATE, COUNTRY, POSTALCODE, PHONE, FAX, EMAIL, SUPPORTREPID)
    VALUES
    (61, 'Jill', 'Sky', 'Panda Express', '2343 Blue Pl', 'Calgary', 'AB', 'Canada', 'T5K 2N1',
    '1-432-234-4333', '1-234-343-2343', 'jillsky@gmail.com', 3);
/

--2.4 UPDATE


